family/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^summary/', include('summary.urls')),
]

summary/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^(?P<Person_id>[0-9]+)/$', views.Person_detail, name = "detail"),
]

summary/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
	name = models.CharField(max_length = 200)
	gender = models.CharField(max_length = 200)
	relation = models.CharField(max_length = 200)
	def __str__(self):
		return self.name + ' - ' + self.relation
class Event(models.Model):
	person = models.ForeignKey(Person, on_delete = models.CASCADE)
	event_name = models.CharField(max_length = 200)

	def __str__(self):
		return self.event_name

summary/views.py
from django.shortcuts import render

from .models import Person
from django.http import HttpResponse
#from django.template import loader
from django.shortcuts import render, get_object_or_404

def index(request):
	all_Persons = Person.objects.all()
	#html = ''
	#for item in all_Persons:
	#	url = '/summary/' + str(item.id) + '/'
	#	html += '<a href = "' + url + '">' + item.name + '</a><br>'
	#template = loader.get_template('summary/index.html')
	context = {
		'all_persons': all_Persons,
	}
	#return HttpResponse(template.render(context,request))
	return render(request, 'summary/index.html', context)

def Person_detail(request, Person_id):
	#return HttpResponse("<h2>details for Person ID" + str(Person_id) +"</h2>")
	#try:
	#	person = Person.objects.get(pk = person_id)
	#except person.DoesNotExist:
	#	raise Http404("Person does not exist")
	person = get_object_or_404(Person, pk = Person_id)
	return render(request, 'summary/detail.html', {'Person' : person})

summary/templates/summary/detail.html
<h1>{{Person.name}}</h1>

<h3>{{Person.gender}}</h3>

<ul>
	{%for event in Person.event_set.all%}
	<li>{{event.event_name}}</li>
	{%endfor%}
</ul>

summary/templates/summary/index.html
{% if all_persons %}

	<h2> Here's all Persons: </h2>

	<ul>
	
		{% for person in all_persons %}

		<li><a href = "{% url 'detail' person.id%}"> {{ person.name }}</a></li>
	
		{% endfor %}
	</ul>

{%else %}
	<p>You don't have any Persons recorded</p>
{% endif%}